### ISSUE TITLE
高德距离报警的节点，方式选骑行的话，会报错

### ISSUE THREAD

**Issue by dukewang2002** [smarthomefans/node-red-contrib-gaode#3]
高德距离报警的节点，方式选骑行的话，会报错，看了一下代码可能是高德API升级了，目前骑行规划的API是 (https://restapi.amap.com/v4/direction/bicycling?parameters) 您节点中使用的 (https://restapi.amap.com/v3/direction/bicycling?parameters) 这个可能已经不支持了，麻烦您升级修改一下，谢谢！

**Comment by yaming116** [comment]
最新版本都支持了
