### ISSUE TITLE
地址描述与地图图片坐标系不一致

### ISSUE THREAD

**Issue by dukewang2002** [smarthomefans/node-red-contrib-gaode#4]
这个高德节点，GPS坐标直接输入的话，地址描述location是正确的，但是地图偏移非常严重，如果修正成高德坐标，地图显示正常了，但是地址描述location又不对了，看代码LOCATION提取时坐标是做过修正的，但是IMAGE没修正，能不能请花神修补一下把image的坐标也做一下修正呢？谢谢！

**Comment by yaming116** [comment]
最新版版都支持了
